### ISSUE TITLE
你好！运行程序的时候，段错误是什么原因？

### ISSUE THREAD

**Issue by Cubexp** [xanarry/onlinejudge#2]
你好！运行程序的时候，段错误是什么原因？自己手动运行编译后的Main是可以运行，且结果没错的。
运行结果:
[![OJsZs1.png](https://s1.ax1x.com/2022/05/09/OJsZs1.png)](https://imgtu.com/i/OJsZs1)

**Comment by xanarry** [comment]
搞定了吗？文件路径再检查一下呢&nbsp;


熊洋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月9日(星期一) 晚上8:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [xanarry/onlinejudge] 请问能给个测试数据样例吗？ (Issue #2)





 
你好！请问能给个测试数据样例吗？
 我按照README里面的路径，添加的评测用例但还是读取不到。
 
 
 运行结果:
 新的评测请求
 submitID: 0
 problemID: 1
 timeLimit: 1000
 memLimit: 65536
 language: c
 codeLength: 116
 submitDir: ./tmp/0
 sorcecodePath: ./tmp/0/Main.c
 compileCmd: gcc ./tmp/0/Main.c -o ./tmp/0/Main -O2 -Wall -lm --static -std=c99
 executeCmd: ./tmp/0/Main ./tmp/0/Main
 codeLength: 10
 test points input file:
 1:(null)
 2:(null)
 3:(null)
 4:(null)
 5:(null)
 6:(null)
 7:(null)
 8:(null)
 9:(null)
 10:(null)
 compile ret: 0

**Comment by Cubexp** [comment]
> 

你好！感谢回复！解决了题目测试用例读取的问题。但进行测试的时候，读不到./tmp/下面用户程序生成的结果数据，程序输出如下：
[![OdOVJ0.png](https://s1.ax1x.com/2022/05/11/OdOVJ0.png)](https://imgtu.com/i/OdOVJ0)
环境：
Ubuntu 22.04 LTS
gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1) 
如果关闭程序后不删除tmp下用户程序结果，程序读取tmp下用户程序生成的结果数据，是能读取到，但运行的时候，又读取不到。

**Comment by Cubexp** [comment]
你好!己经找到报错原因了,谢谢!
